exports = function(arg) {
  return {
    'andf-mongodb':           'andrew.feierabend@10gen.com',
    'atsansone':              'tony.sansone@10gen.com',
    'ccho-mongodb':           'chris.cho@10gen.com',
    'danielborowski':         'daniel.borowski@10gen.com',
    'i80and':                 'andrew.aldridge@10gen.com',
    'jeff-allen-mongo':       'jeffrey.allen@10gen.com',
    'jwilliams-mongo':        'john.williams@10gen.com',
    'ljhaywar':               'lauren.schaefer@mongodb.com',
    'mango-db':               'claire.goeckner-wald@10gen.com',
    'melissamahoney-mongodb': 'melissa.mahoney@mongodb.com',
    'mongomoe':               'mohammad.hunan@10gen.com',
    'nathan-contino-mongo':   'nathan.contino@10gen.com',
    'niccottrell':            'nicholas.cottrell@10gen.com',
    'nlarew':                 'nick.larew@mongodb.com',
    'schmalliso':             'allison.moore@10gen.com',
    'skerschb':               'sue.kerschbaumer@10gen.com',
    'sophstad':               'sophie.stadler@10gen.com',
    'steveren':               'steve.renaker@10gen.com',
    'terakilobyte':           'nathan.leniz@10gen.com',
    'zach-carr':              'zach.carr@10gen.com',
    'kanchana-mongodb':       'kanchana.sekhar@10gen.com', 
    'tahiya-mongo':           'tahiya.chowdhury@10gen.com', 
    'greggb' :                'gregg.brewster@10gen.com',
    'jdrumgoole':              'joe.drumgoole@10gen.com',
    'kenwalger':              'ken.alger@mongodb.com',
    'MaBeuLux88':             'maxime.beugnet@mongodb.com',
    'nraboy':                 'nicolas.raboy@10gen.com',
    'kukicado':               'adnan-ado.kukic@10gen.com',
    'madelinezec':            'maddie.zechar@mongodb.com',
    'eshwer':                 'elle.shwer@mongodb.com',
    'rayangler':              'raymund.rodriguez@mongodb.com',
    'GuruPKK':                'guru.kanthasamy@mongodb.com',
    'sarahsimpers':       'sarah.simpers@mongodb.com'
  };
};